//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ans.Net8.Web.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Common {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Common() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ans.Net8.Web.Resources.Common", typeof(Common).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;span title=&quot;Нет&quot;&gt;&amp;nbsp;&lt;/span&gt;.
        /// </summary>
        public static string Html_CellFalse {
            get {
                return ResourceManager.GetString("Html_CellFalse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;span class=&quot;text-success text-nowrap&quot;&gt;&lt;i class=&quot;bi-check-lg&quot;&gt;&lt;/i&gt;да&lt;/span&gt;.
        /// </summary>
        public static string Html_CellTrue {
            get {
                return ResourceManager.GetString("Html_CellTrue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Да.
        /// </summary>
        public static string Html_EditChecked {
            get {
                return ResourceManager.GetString("Html_EditChecked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to нет.
        /// </summary>
        public static string Html_EditFalse {
            get {
                return ResourceManager.GetString("Html_EditFalse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to да.
        /// </summary>
        public static string Html_EditTrue {
            get {
                return ResourceManager.GetString("Html_EditTrue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нет.
        /// </summary>
        public static string Html_ViewFalse {
            get {
                return ResourceManager.GetString("Html_ViewFalse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Да.
        /// </summary>
        public static string Html_ViewTrue {
            get {
                return ResourceManager.GetString("Html_ViewTrue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}, доб. {1}.
        /// </summary>
        public static string Template_PhoneAddon {
            get {
                return ResourceManager.GetString("Template_PhoneAddon", resourceCulture);
            }
        }
    }
}
