//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ans.Net8.Web.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Forms {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Forms() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ans.Net8.Web.Resources.Forms", typeof(Forms).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отмена.
        /// </summary>
        public static string Button_Cancel {
            get {
                return ResourceManager.GetString("Button_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Создать.
        /// </summary>
        public static string Button_Create {
            get {
                return ResourceManager.GetString("Button_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Создать и продолжить редактирование.
        /// </summary>
        public static string Button_CreateAndEdit {
            get {
                return ResourceManager.GetString("Button_CreateAndEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить.
        /// </summary>
        public static string Button_Delete {
            get {
                return ResourceManager.GetString("Button_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Назад.
        /// </summary>
        public static string Button_Return {
            get {
                return ResourceManager.GetString("Button_Return", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сохранить.
        /// </summary>
        public static string Button_Save {
            get {
                return ResourceManager.GetString("Button_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Загрузить.
        /// </summary>
        public static string Button_Upload {
            get {
                return ResourceManager.GetString("Button_Upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Элемент содержит данные. Удаление запрещено!.
        /// </summary>
        public static string Html_DeleteDisable {
            get {
                return ResourceManager.GetString("Html_DeleteDisable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы уверены, что следует удалить этот элемент?.
        /// </summary>
        public static string Html_DeleteQuestion {
            get {
                return ResourceManager.GetString("Html_DeleteQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to создание: {0}.
        /// </summary>
        public static string Template_ItemDateCreate {
            get {
                return ResourceManager.GetString("Template_ItemDateCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to редактирование: {0}.
        /// </summary>
        public static string Template_ItemDateUpdate {
            get {
                return ResourceManager.GetString("Template_ItemDateUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;nbsp;&lt;a href=&quot;{0}&quot; class=&quot;text-info&quot; target=&quot;_blank&quot; title=&quot;Справка...&quot;&gt;&lt;i class=&quot;fas fa-question-circle&quot;&gt;&lt;/i&gt;&lt;/a&gt;.
        /// </summary>
        public static string Template_MoreLink {
            get {
                return ResourceManager.GetString("Template_MoreLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пример: &lt;code&gt;{0}&lt;/code&gt;.
        /// </summary>
        public static string Template_Sample {
            get {
                return ResourceManager.GetString("Template_Sample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to добавить.
        /// </summary>
        public static string ToolTip_Add {
            get {
                return ResourceManager.GetString("ToolTip_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to удалить.
        /// </summary>
        public static string ToolTip_Delete {
            get {
                return ResourceManager.GetString("ToolTip_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to просмотр.
        /// </summary>
        public static string ToolTip_Details {
            get {
                return ResourceManager.GetString("ToolTip_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to редактировать.
        /// </summary>
        public static string ToolTip_Edit {
            get {
                return ResourceManager.GetString("ToolTip_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to обязательное поле.
        /// </summary>
        public static string ToolTip_Required {
            get {
                return ResourceManager.GetString("ToolTip_Required", resourceCulture);
            }
        }
    }
}
